-- ============================================================
-- Merry's Way Coffee Shop — Supabase Schema
-- Run this in Supabase SQL Editor
-- ============================================================
-- Naming convention : coffee_shop_{table}
-- user_id           : email (text) everywhere
-- session_id        : UUID, generated by frontend, stored in localStorage
-- Soft deletes      : none — cancelled orders are hard deleted
-- Messages          : persist per session, cleared when new session starts
-- ============================================================


-- ── Profiles (user memory / preferences) ─────────────────────────────────────

create table if not exists coffee_shop_profiles (
  user_email   text         primary key,
  name         text,
  likes        jsonb        not null default '[]',
  dislikes     jsonb        not null default '[]',
  allergies    jsonb        not null default '[]',
  last_order   text,
  feedback     jsonb        not null default '[]',
  location     text,
  last_updated timestamptz  not null default now()
);

alter table coffee_shop_profiles enable row level security;

create policy "Users can read own profile"
  on coffee_shop_profiles for select
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can insert own profile"
  on coffee_shop_profiles for insert
  with check (auth.jwt() ->> 'email' = user_email);

create policy "Users can update own profile"
  on coffee_shop_profiles for update
  using (auth.jwt() ->> 'email' = user_email);


-- ── Products (menu items) ─────────────────────────────────────────────────────

create table if not exists coffee_shop_products (
  id          uuid         primary key default gen_random_uuid(),
  name        text         not null unique,
  category    text,
  description text,
  price       float        not null,
  rating      float,
  ingredients jsonb        not null default '[]',
  image_url   text,
  created_at  timestamptz  not null default now()
);

-- Public read — anyone can browse the menu
alter table coffee_shop_products enable row level security;

create policy "Public can read products"
  on coffee_shop_products for select
  using (true);


-- ── Orders ────────────────────────────────────────────────────────────────────
-- status: pending | confirmed
-- cancelled orders are hard deleted

create table if not exists coffee_shop_orders (
  id          uuid         primary key default gen_random_uuid(),
  user_email  text         not null,
  items       jsonb        not null,   -- [{name, quantity, per_unit_price, total_price}]
  total       float        not null,
  status      text         not null default 'pending',
  updated_at  timestamptz  not null default now()
);

create index if not exists coffee_shop_orders_user_status_idx
  on coffee_shop_orders (user_email, status);

alter table coffee_shop_orders enable row level security;

create policy "Users can read own orders"
  on coffee_shop_orders for select
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can insert own orders"
  on coffee_shop_orders for insert
  with check (auth.jwt() ->> 'email' = user_email);

create policy "Users can update own orders"
  on coffee_shop_orders for update
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can delete own orders"
  on coffee_shop_orders for delete
  using (auth.jwt() ->> 'email' = user_email);


-- ── Sessions ──────────────────────────────────────────────────────────────────

create table if not exists coffee_shop_sessions (
  session_id   uuid         primary key,  -- generated by frontend
  user_email   text         not null,
  created_at   timestamptz  not null default now(),
  last_active  timestamptz  not null default now()
);

create index if not exists coffee_shop_sessions_user_idx
  on coffee_shop_sessions (user_email);

alter table coffee_shop_sessions enable row level security;

create policy "Users can read own sessions"
  on coffee_shop_sessions for select
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can insert own sessions"
  on coffee_shop_sessions for insert
  with check (auth.jwt() ->> 'email' = user_email);

create policy "Users can update own sessions"
  on coffee_shop_sessions for update
  using (auth.jwt() ->> 'email' = user_email);


-- ── Messages ──────────────────────────────────────────────────────────────────
-- One row per session — all messages stored as JSONB array
-- [{role: 'user'|'assistant', content: string, timestamp: string}]

create table if not exists coffee_shop_messages (
  session_id   uuid         primary key references coffee_shop_sessions(session_id) on delete cascade,
  user_email   text         not null,
  messages     jsonb        not null default '[]',
  updated_at   timestamptz  not null default now()
);

alter table coffee_shop_messages enable row level security;

create policy "Users can read own messages"
  on coffee_shop_messages for select
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can insert own messages"
  on coffee_shop_messages for insert
  with check (auth.jwt() ->> 'email' = user_email);

create policy "Users can update own messages"
  on coffee_shop_messages for update
  using (auth.jwt() ->> 'email' = user_email);

create policy "Users can delete own messages"
  on coffee_shop_messages for delete
  using (auth.jwt() ->> 'email' = user_email);
